; Information for the current test process

; Paths of specify working directories
[Paths]
FolderPath = C:\Users\K90011729\OneDrive - Kimball Electronics\Desktop\Proyectos\LogSpy\LogSpy\data\samples
; OutputLog = 

[Process]
StationName = STA_FNLFUNC208

[WSConnector]
WSConnector.Dll = C:\Users\K90011729\OneDrive - Kimball Electronics\Desktop\Proyectos\LogSpy\LogSpy\WsConnector\WSConnector.dll
Newtonsoft.Json.Dll = C:\Users\K90011729\OneDrive - Kimball Electronics\Desktop\Proyectos\LogSpy\LogSpy\WsConnector\Newtonsoft.Json.dll

[SQL server]
Server = 095DESIGN3D,1433
Password = T3stPa$$word
Database = FCT DATA
Userid = sa
Driver = {ODBC Driver 17 for SQL Server}
